%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/banked.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/bounce.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/bounce_struct.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/edit.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/fixeddemo.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/fizzbuzz.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/spriteballs.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/grep.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/udg.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/ulagfx.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/zxbgfxtst.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/feature_test.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/cal.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/calMonth.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/nextparam.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/rubik.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/regextst.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/libcompile.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/spaceshooter.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/spaceshooter.spr /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/spaceshooter.til /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/spaceshooter.pal /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/sudoku.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/PUZZLE01.txt /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/hexvw.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/hexedit.znc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/font.inc /zdev/examples/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd tests/crttst.znc /zdev/examples/

%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/ay.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/crt.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/crtedit.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/ctype.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/io.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/esxbase.inc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/fileio.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/dirinfo.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/memory.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/rnd.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/regex.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/sprite.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/string.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/printf.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/sprintf.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/kbd.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/mmu.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/cmdline.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/dot.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/dotn.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/zxbgfx.znc /zdev/

rem Libraries used with permission from Iáń Júkéś
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/datetime.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/intToMonth.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/joystick.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/mouse.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/strcontains.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/strtoint.znc /zdev/
%1/../../emulator/hdfmonkey put %1/../../sdcard/tbblue-dev.sd znclib/version.znc /zdev/

%1/../../emulator/hdfmonkey get %1/../../sdcard/tbblue-dev.sd /zdev/examples/testrunner.bas tests/testrunner.bas
%1/../../emulator/hdfmonkey get %1/../../sdcard/tbblue-dev.sd /zdev/examples/zncdemo.bas tests/zncdemo.bas
%1/../../emulator/hdfmonkey get %1/../../sdcard/tbblue-dev.sd /zdev/zide.bas tests/zide.bas